name: Deploy example website

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch
    # paths:
    #   - 'example-site/**'  # Trigger only if changes occur inside the 'example' folder

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout gh-pages-deploy branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages-deploy  # Checkout gh-pages-deploy branch to make changes

    - name: Clear gh-pages-deploy branch content
      run: |
        git ls-files -z | grep -v '\.gitignore' | xargs -0 git rm -f # Remove all files in gh-pages-deploy branch except .gitignore 

    - name: Copy folder contents from main branch
      run: |
        git checkout main -- example-site/dist  # Checkout only the 'example-site/dist' folder from main branch
        mv example-site/dist/* .  # Move contents of the 'example-site/dist' folder to the root of gh-pages-deploy branch
        rm -rf example-site  # Clean up the folder path

    - name: Commit changes
      run: |
        git add .
        timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')  # Get current UTC timestamp in ISO 8601 format
        git commit -m "deploy $timestamp"  # Use the UTC timestamp as the commit message
        git push origin gh-pages-deploy  # Push changes to the deploy branch
